version: '3.8'

services:
  basededatos:
    image: mysql:8.0
    container_name: mysql_login
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: empresas
    ports:
      - "3306:3306"